version: "3.6"

services:
  reserve_app:
    environment:
      - APP_MONGO_USER=${APP_RESERVE_MONGO_USER}
      - APP_MONGO_PASS=${APP_RESERVE_MONGO_PASS}
      - MONGO_PORT=${RESERVE_MONGO_PORT}
      - MONGO_DB=${APP_RESERVE_MONGO_DB}
    build:
      context: ./backend/reserve/app
      dockerfile: build/dev/Dockerfile
    volumes:
      - ./backend/reserve/app/src/:/home/node/app
    ports:
      - 3457:3000
    depends_on:
      - reserve_mongo
    networks:
      - constrsw

  reserve_mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${RESERVE_MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${RESERVE_MONGO_ROOT_PASSWORD}
      - APP_MONGO_HOST=${RESERVE_MONGO_HOST}
      - MONGO_PORT=${RESERVE_MONGO_PORT}
      - MONGO_ROOT_USER=${RESERVE_MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASS=${RESERVE_MONGO_ROOT_PASSWORD}
      - APP_MONGO_USER=${APP_RESERVE_MONGO_USER}
      - APP_MONGO_PASS=${APP_RESERVE_MONGO_PASS}
      - APP_MONGO_DB=${APP_RESERVE_MONGO_DB}
    container_name: reserve_mongo
    build: ./backend/reserve/mongo
    ports:
      - "${RESERVE_MONGO_PORT}:27017"
    volumes:
      - constrsw-pgdata:${DB_RESERVE_MONGO_DATA}:rw
    networks:
      - constrsw

  # auth:
  #   build:
  #     context: ./backend/auth
  #     dockerfile: build/dev/Dockerfile
  #   volumes:
  #       - ./backend/auth/src/:/home/node/app
  #   ports:
  #     - 3456:3456
  #   networks:
  #     - constrsw
  #   depends_on:
  #     - keycloak
  # keycloak:
  #   environment:
  #     - DB_VENDOR=${DB_KEYCLOAK_VENDOR}
  #     - DB_ADDR=postgres
  #     - DB_PORT=5432
  #     - DB_DATABASE=${DB_KEYCLOAK_DATABASE}
  #     - DB_USER=${DB_KEYCLOAK_USER}
  #     - DB_PASSWORD=${DB_KEYCLOAK_PASSWORD}
  #     - KEYCLOAK_USER=${KEYCLOAK_USER}
  #     - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
  #   build: ./backend/keycloak/build/dev
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - constrsw
  #   depends_on:
  #     - postgres
  # postgres:
  #   environment:
  #     - POSTGRES_FIX_OWNERSHIP=1
  #     - POSTGRES_DB=${DB_POSTGRES_DATABASE}
  #     - POSTGRES_USER=${DB_POSTGRES_USERNAME}
  #     - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
  #     - DB_KEYCLOAK_DATABASE=${DB_KEYCLOAK_DATABASE}
  #     - DB_KEYCLOAK_USER=${DB_KEYCLOAK_USER}
  #     - DB_KEYCLOAK_PASSWORD=${DB_KEYCLOAK_PASSWORD}
  #   build: ./backend/postgres
  #   ports:
  #     - ${DB_POSTGRES_PORT}:5432
  #   volumes:
  #     - constrsw-pgdata:${DB_POSTGRES_DATA}:rw
  #   networks:
  #     - constrsw

volumes:
  constrsw-pgdata:
    external: true

networks:
  constrsw:
